services:
  to-do-frontend:
    build:
      context: ./frontend
    image: to-do-frontend
    container_name: to-do-frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run serve

  to-do-backend: 
    build:
      context: ./backend
    image: to-do-backend
    container_name: to-do-backend
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - to-do-mysql
  
  to-do-mysql:
    image: mysql:5.7
    container_name: to-do-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: