CREATE DATABASE IF NOT EXISTS tododb;
CREATE USER IF NOT EXISTS 'tdusr'@'%' IDENTIFIED BY 'tdusr';
GRANT ALL PRIVILEGES ON tododb.* TO 'tdusr'@'%';
FLUSH PRIVILEGES;

USE tododb;

CREATE TABLE `TEST` (
  `test_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`test_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;

CREATE TABLE `USERS` (
  `usr_id` INT NOT NULL AUTO_INCREMENT,
  `usr_name` VARCHAR(45) NOT NULL,
  `birth` VARCHAR(6) NULL,
  `email` VARCHAR(100) NULL,
  `pwd` VARCHAR(100) NOT NULL,
  `reg_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usr_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;

CREATE TABLE `TODOLISTS` (
  `list_id` INT NOT NULL AUTO_INCREMENT,
  `usr_id` INT NOT NULL,
  `list_title` VARCHAR(1024) NULL,
  `upd_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `reg_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`list_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;

CREATE TABLE `TODOITEMS` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `list_id` INT NOT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT 0,
  `item_title` TEXT NOT NULL,
  `is_cpt` VARCHAR(1) NULL DEFAULT 'N',
  `due_date` TIMESTAMP NULL,
  `upt_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `reg_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;


CREATE TABLE quotes (
    `quote_id` INT NOT NULL AUTO_INCREMENT,
    `quote` TEXT NOT NULL,
    `author` VARCHAR(255) NOT NULL,
    `date` DATE NOT NULL,
    `reg_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`quote_id`),
    UNIQUE (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;